### ISSUE TITLE
Rationale?

### ISSUE THREAD

**Issue by scottcc** [GitHawkApp/MessageViewController#21]
Hey, this looks interesting - I'm curious what (if anything) was missing from the heavy-inspiration-source of SlackTextViewController that caused you to create this library? Why would one use MessageViewController instead?

**Comment by rnystrom** [comment]
Hey @scottcc ! I was using Slacks control for GitHawk but I kept having to patch the project to fix bugs or make tiny customizations. Finally decided that I needed more control and a decoupled design. This this project!

My main advantages:

- Use autocomplete on its own (attach to random text views)
- iPhone X support
- No iOS 11 hacks 
- Simpler animations
- Protocols instead of method overrides

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hipwelljo** [comment]
Also, it has been stated slack isn't really continuing development on it - see the "is this a dead library" issue over there.

**Comment by scottcc** [comment]
These are *great* reasons to have on the main README as to "why" 😉 to use this app, IMHO.
