### ISSUE TITLE
Do an accessibility audit

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/MessageViewController#34]
Check if the elements are properly accessible in VoiceOver and improve if needed.

**Comment by hipwelljo** [comment]
I've completed an audit. I'm not finding much! 

I did notice the text view is behaving in a funky fashion. Tapping it to focus it, it only reads the line of text that you tapped, rather than the entire text view content. Comparing that to Messages, when you tap in the the text view, it reads the entire contents. Note that when you don't tap in the text view but rather swipe between elements, it properly highlights the entire text view and reads it all.

The attachment button doesn't do anything, but it also doesn't do anything when not using VO.

**Comment by BasThomas** [comment]
That is an awesome audit, thanks @hipwelljo! Also, I think we can and should look into fixing all of the points you mentioned.

Is this something you want to take a look at? Maybe create separate issues for all of the points?

**Comment by hipwelljo** [comment]
I'll go ahead and create separate issues. I'm not sure how exactly to solve them atm though, and likely won't have time to look into it unfortunately.

**Comment by BasThomas** [comment]
Don’t worry! Thanks so much for reporting. Closing this in favor of the more granular tickets. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
