### ISSUE TITLE
Not respecting bottom inset when adjusting offset for keyboard

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/MessageViewController#70]
I knew something was off. Fixed locally will push.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by siefix** [comment]
Is there any way to make this respect the tabBar (if you have one?)

The only way I found for it to adjust for the tab bar is with 
`tabBarController?.tabBar.isHidden = true`

However if you use something like (animatable) 
`tabBarController?.tabBar.frame.origin = CGPoint(x: 0, y: frameHeight - tabBarHeight)`

The `messageView` will still show the extra 49pts of tabbarheight


Or.....**any insight into how Instagram does it**?! :) (not sure if you use MessageViewController)

Looks like you might be doing `present(_:animated:completion:)` instead of `pushViewController(_ viewController: UIViewController, animated: Bool)` and then are using some sort of custom right/left `UIViewControllerAnimatedTransitioning`?


![img_5203](https://user-images.githubusercontent.com/20218698/44867750-59463500-ac4e-11e8-8842-a1af98d40913.PNG)

**Comment by rnystrom** [comment]
@siefix can you open a new issue? This was fixed, I forgot to close (can’t find hash while traveling).

Instagram doesn’t use this 😉

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
