### ISSUE TITLE
How to integrate MessageViewController with MessageKit or JSQMessageViewController

### ISSUE THREAD

**Issue by JulienKode** [GitHawkApp/MessageViewController#74]
This library is really nice, but I'm wondering how to integrate it with others libraries to create a chat 

MessageKit has it's own Controller to inherit and MessageViewController too, what is the best pratique to mix theses libraries ? 

I've try to make a parent controller with MessageViewController and use JSQMessageViewController as a child (I know this library is deprecated) 

I've try to make the configuration of MessageViewController in both viewdidload but it crash because of UI constraint 

Thank you so much for your help

**Comment by SD10** [comment]
Hey @JulienKode,

This library is not compatible with MessageKit or JSQMessagesViewController. They’re 3 separate solutions to providing a chat UI. It’s not really possible to replace the controllers from JSQMVC or MessageKit with this controller as their controllers are so tightly coupled to the rest of the library. Both JSQMVC and MessageKit don’t require you to dequeue cells for example, you just have to adopt the respective delegate and return your data model. If you try to swap out this controller the rest of the library really wouldn’t know how to operate.

MessageViewController is a very lightweight solution for chat UI. I recommend you use it as is and provide your own cells rather than try to mix and match libraries. It will save you a ton of time in the long run

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@JulienKode I think you're on the right track. You can use this library for the textView and keyboard handling. Then handle your collectionView/tableView and all the cells you need for your messages yourself

**Comment by rnystrom** [comment]
Closing seems like this is answered. GitHawk did exactly that: we use the control for text entry and then use our own collection view architecture to display data. This design lets you have control over how stuff is rendered and updated.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JulienKode** [comment]
Thanks for your advice @SD10 @rnystrom 

You just have to use a basic collectionView or you made a lot of optimisation ?

**Comment by rnystrom** [comment]
IGListKit

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
